---
title: "Introduction to Linux - Exercises"
author: "Angelika Merkel"
---

### Exercise 1: 

Go to the directory '/home' and list its content. How many user with starting with 'f'? How many regular files aside from directories?

**Answer**
```bash
 cd /home
 ls .
```


### Exercise 2: 

In your home directory create a new directory called 'analysis'. Copy the file peaks.bed from the folder /home/shared/ there. Now, create a softlink to the original file and call the file 'newpeaks.bed'. 

Finally, list all files that end with ‘.bed’ in a single command. What command did you use? 

**Answer**
```bash
# go to your home directory
 cd ~

# create directory
 mkdir analysis                     

# enter 'analysis' directory 
 cd analysis
 
# copy 'peaks.bed' to current directory 
 cp /home/shared/peaks.bed .  

# create softlink 
 ln -s /home/shared/peaks.bed -n newpeaks.bed  

# list all files ending in '.bed' in all three directories
 ls *.bed
```

::: {.callout-tip}
You can use the `tree` command to get a more visual overview of your directory structure:
:::

 

### Exercise 3: 

Is bzip2 or gzip the better compression? Which algorithm compresses peaks.bed more? 

**Answer**
```bash
# create two extra copies of 'peaks.bed'
 cp peaks.bed peaks1.bed
 cp peaks.bed peaks2.bed

# compress one file with gzip
 gzip peaks1.bed

# compress the other file wit bzip2
 bzip2 peaks2.bed

# compare file sizes with ls
 ls -lth

# => the file compressed with bzip2 is slightly smaller (6.1K) than the one compressed with gzip (6.4K)
```


### Exercise 4

Extract the first and last 10 lines of the file peaks.bed into a new file. How many characters does this file have?

**Answer**
```bash
# extract the first 10 lines
 head -10 peaks.bed > head.peaks
 
# extract the last 10 lines and append to the previous file
 tail -10 peaks.bed >> head.peaks
 
# count the number of characters
 wc -c head.peaks
```

### Exercise 5:

Create a file from the first 10 lines of peaks.bed containing only the second and fifth column, where the second column is sorted by increasing size and the fifth column by decreasing size. 

How many characters does the last line of this file have? 

**Answer**
```bash
# extract the first 10 lines, slice column 2, sort numerical and store output in a file
 head -10 peaks.bed | cut -f 2 |sort -n > column2

# do the same but with column 5 and sort in reverse order.
# then join output with previous file, extract last line and count number of characters (=12)
 head -10 peaks.bed | cut -f 5 |sort -nr| paste column 2 - | tail -1| wc -c
```

 

### Exercise 6:

What is the highest and lowest value in column 5 on chrM?  

**Answer**
```bash
# find all lines with pattern 'chrM', slice column 5, sort numerical, 
# extract first and last line
grep -w chrM peaks.bed | cut -f 5| sort -n| head -1
grep -w chrM peaks.bed | cut -f 5| sort -n| tail -1

```

### Exercise 7:

Write a script, that for any given directory lists all files it contains and counts the number of characters of all regular files it contains.

**Answer**
```bash
#! /bin/bash

### Author: Angelika Merkel
### Date: 30/11/2022

###############################################################################
### Description:
### Script script, that for any given directory lists all files it contains and
### counts the number of characters of all regular files it contains.

###############################################################################
# assign the script's first argument to a meaningful variable
DIR=$1

# loop over all elements listed in the specified directory
for i in `ls $DIR`
 do
 
 # test if the element listed is a regular file (else could be a directory)
  if [ -f "$i" ]                         
  
  # if true, count all characters within the file and return with a message
    then
      CHAR=`cat $i| wc -c`
      echo $i ":" $CHAR "characters"
  
  # close conditional
  fi
  
# close for loop
done
```

Finally, to run the script:
```bash
 chmod a+x myscript.sh       # make the file executable
 ./myscript.sh               # run
```


