---
title: "IJC Computing"
---

### Introduction to the IJC Computing Infrastructure

The Bioinformatics Unit (together with the IT team) provides this seminar to introduce newcomers to the IJC to the institute's computing infrastructure. It also serves to keep established researchers updated with latest changes or additions by IT. 


**Topics covered:**

* Computational infrastructure and resources
* File sharing (oneDrive/nextCloud/sharedFolder)
* Data sharing (ftp/sftp)
* The IJC network and remote connections
* IJC's high-performance computing cluster (HPC) 


**Materials**

- [Seminar presentation](data/Introduction_to_the_IJC_computing_infrastructure_Overview.June2024.pdf) 
 
 
<br/>

### Computations with the IJC HPC Cluster 'Minastirith'


For bioinformaticians specifically, we provide a practical training session on how to use the IJC HPC cluster (aka 'minastirith') for scientific computation. This session is aimed at users with an [Intermediate]{.underline} level and requires basic knowledge of Linux and Bash. We strongly recommend to attend our Beginners course 'Introduction to Linux and the Shell' beforehand.


**Topics covered:**

* The SLURM job scheduler
* Submitting jobs with sbatch
* Monitoring and controlling jobs
* Serial and array jobs
* Requesting resources

**Materials:**

- [Workshop presentation](data/Introduction_to_the_IJC_HPC.June2024.pdf)
